# Generated by Django 3.0.8 on 2020-07-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_watchlistentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='currentAmount',
        ),
        migrations.AddField(
            model_name='auction',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
